### ISSUE TITLE
Improvement of UI

### ISSUE THREAD

**Issue by nzivo** [paulmunyao/Burger-Palace#1]
Hi Paul, I thought to sent my comment as an issue. I like the choice of color and images on some parts. The font might be what you need to work on next and symmetry in the layout

**Comment by paulmunyao** [comment]
Thanks John I'll work on that

**Comment by paulmunyao** [comment]
> Hi Paul, I thought to sent my comment as an issue. I like the choice of color and images on some parts. The font might be what you need to work on next and symmetry in the layout

Thanks John I'll work on that

**Comment by nzivo** [comment]
great
